# Generated by Django 4.2.13 on 2024-07-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memes/')),
                ('name', models.CharField(max_length=225)),
                ('season', models.PositiveSmallIntegerField()),
                ('episode', models.PositiveSmallIntegerField()),
                ('duration', models.TimeField()),
                ('tags', models.CharField(max_length=225)),
            ],
        ),
    ]
