# Generated by Django 4.2.13 on 2024-07-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memes',
            name='episode',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memes/'),
        ),
        migrations.AlterField(
            model_name='memes',
            name='season',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memes',
            name='tags',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
