# Generated by Django 4.2.13 on 2024-07-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_alter_memes_duration_alter_memes_episode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='video',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
