# Generated by Django 4.2.13 on 2024-07-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_memes_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='duration',
        ),
    ]
