# Generated by Django 4.2.13 on 2024-07-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_remove_memes_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memes/files/images/'),
        ),
        migrations.AlterField(
            model_name='memes',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='memes/files/images/'),
        ),
    ]
