# Generated by Django 4.2.13 on 2024-07-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_alter_memes_image_alter_memes_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='video',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
