# Generated by Django 4.2.13 on 2024-07-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0006_alter_memes_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video'), ('gif', 'gif'), ('all', 'all')], max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='memes',
            name='video_link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='memes',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='memes/files/images/'),
        ),
    ]
